config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'
  devise_for :users

  authenticated :user do
    root to: 'dashboard#show', as: :user_root
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :categories

  resources :accounts
  resources :transactions do
    collection do
      get :read
      post :import
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy

  enum :account_type, { checking: 'checking', savings: 'savings' }, suffix: :type

  def calculate_balance
    transactions.credit_type.sum(&:amount) - transactions.debit_type.sum(&:amount)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions

  validates :name,
            presence: true,
            uniqueness: {
              scope: :user,
              message: 'Category already exists.',
              case_sensitive: false
            }

  scope :ordered, -> { order(id: :desc) }
  paginates_per 10
end

app/models/default_category.rb
class DefaultCategory < ApplicationRecord
  validates :name,
            presence: true,
            uniqueness: {
              message: 'Default Category already exists.',
              case_sensitive: false
            }
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :category

  enum :transaction_type, { debit: 'debit', credit: 'credit' }, suffix: :type

  scope :ordered, -> { order(date: :desc) }
  paginates_per 10

  after_commit :update_account_balance, on: %i[create update destroy]
  def update_account_balance
    account.update(current_balance: account.calculate_balance)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :accounts, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :transactions, through: :accounts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def calculate_total_debit
    transactions.debit_type.sum(&:amount)
  end

  def calculate_total_credit
    transactions.credit_type.sum(&:amount)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[show edit update destroy]

  def index
    @accounts = current_user.accounts
  end

  def show; end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    @account.user = current_user

    if @account.save
      redirect_to accounts_path, notice: 'Account was succesfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @account.update(account_params)
      redirect_to accounts_path, notice: 'Account was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @account.destroy
    redirect_to accounts_path, notice: 'Account was deleted successfully.'
  end

  private

  def account_params
    params.require(:account).permit(:name, :account_type, :account_number, :bank_name, :owner_name, :current_balance)
  end

  def set_account
    @account = Account.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # include Pundit::Authorization

  # Pundit: allow-list approach
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  # private

  # def skip_pundit?
  #   devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  # end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = current_user.categories.page(params[:page])
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      redirect_to categories_path, notice: "Category was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: "Category was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: "Category was successfully destroyed."
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
    @debits = current_user.transactions.debit_type.group_by_month(:date, format: "%b %Y").sum(:amount)
    @credits = current_user.transactions.credit_type.group_by_month(:date, format: "%b %Y").sum(:amount)

    @labels = @debits.keys
    @series = [@debits.values, @credits.values]

    category_chart_data = current_user.transactions.group(:category).sum(:amount)
    @category_chart_labels = category_chart_data.keys.map(&:name)
    @category_chart_series = category_chart_data.values

    @transactions = current_user.transactions.first(10)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]

  def index
    @transactions = current_user.transactions.ordered.page(params[:page])
  end

  def show
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.category = Category.find_or_create_by(name: 'Uncategorized', user: current_user) if params[:transaction][:category].nil?
    if @transaction.save
      redirect_to transactions_path, notice: 'Transaction was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @transaction.update(transaction_params)
      redirect_to transactions_path, notice: 'Transaction was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @transaction.destroy
    redirect_to transactions_path, status: :see_other, alert: 'Transaction was deleted successfully.'
  end

  def read
    @transaction = Transaction.new
  end

  def import
    file = params[:transaction][:file]
    if file.content_type == 'text/csv'
      ImportTransactionsService.new.call(file, params[:transaction][:account_id])
      redirect_to transactions_path, notice: 'Transactions imported successfully.'
    else
      redirect_to new_transaction_path, notice: 'Only CSV files accepted.'
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:date, :description, :transaction_type, :amount, :notes, :account_id, :category_id, :file)
  end

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/_account.html.erb
<div class="col-sm-6 col-lg-6">
  <div class="card d-flex flex-column">
    <div class="row row-0 flex-fill">
      <div class="col-md-3">
        <%= image_tag "westpac-logo.png", class: "w-100 h-100" %>
      </div>
      <div class="col border-start">
        <div class="card-body text-center">
          <h3><%= account.name %></h3>
          <div class="row">
            <div class="col">
              <samp class="text-muted">Bank: <%= account.bank_name.capitalize %></samp>
            </div>
            <div class="col">
              <samp class="text-muted">Type: <%= account.account_type.capitalize %></samp>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <samp class="text-muted">Owner: <%= account.owner_name %></samp>
            </div>
            <div class="col">
              <samp class="text-muted">Number: <%= account.account_number %></samp>
            </div>
          </div>
          <div class="row">
            <div class="col mt-3">
              <strong>Balance: $<%= number_with_precision(account.current_balance, precision: 2) %></strong>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/_form.html.erb
<%= simple_form_for account do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, label: 'Account name' %>
  <%= f.input :account_type, label: 'Account type', collection: Account.account_types.keys.map { |k| [k.titleize, k] }, prompt: "Select an account type" %>
  <%= f.input :bank_name, label: 'Bank name' %>
  <%= f.input :account_number, label: 'Account number' %>
  <%= f.input :owner_name %>
  <%= f.input :current_balance %>
  <%= f.button :submit, class: "mt-3 btn btn-primary w-100" %>
<% end %>

app/views/accounts/create.turbo_stream.erb
<%= turbo_stream.prepend "accounts", @account %>

app/views/accounts/edit.html.erb
<div class="container">
  <%= turbo_frame_tag 'modal' do %>
    <div class="modal-body">
      <h2>Edit account</h2>
      <%= render 'form', account: @account %>
    </div>
  <% end %>
</div>

app/views/accounts/index.html.erb
<div class="page-header d-print-none">
  <div class="container-xl">
    <div class="row g-2 align-items-center">
      <div class="col">
        <h3 class="page-title">Accounts</h3>
      </div>
      <div class="col-auto ms-auto">
        <div class="btn-list">
          <%= link_to new_account_path, data: { turbo_frame: 'modal' }, class: 'btn btn-primary' do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 5l0 14"></path><path d="M5 12l14 0"></path></svg>Add new account
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="page-body">
  <div class="container-xl">
    <div class="row row-deck row-cards">
      <%= render @accounts %>
    </div>
  </div>
</div>
</div>

app/views/accounts/new.html.erb
<div class="container">
  <%= turbo_frame_tag 'modal' do %>
    <div class="modal-body">
      <h2>Add new account</h2>
      <%= render 'form', account: @account %>
    </div>
  <% end %>
</div>

app/views/categories/_category.html.erb
<tr>
  <td><%= category.name %></td>
  <td><%= category.transactions.count %></td>
  <td><%= category.created_at.to_date %></td>
  <td><%= category.updated_at.to_date %></td>
  <td>
    <%= link_to edit_category_path(category), class: 'text-primary', data: { turbo_frame: 'modal' } do %><i class="bi bi-pencil-square"></i><% end %>
    <%= link_to category_path(category), class: 'text-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %><i class="bi bi-trash"></i><% end %>
  </td>
</tr>

app/views/categories/_form.html.erb
<%= simple_form_for category do |f| %>
  <% if category.errors.any? %>
    <div class="error-message alert alert-danger alert-dismissible fade show">
      <%= category.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>
  <%= f.input :name %>
  <%= f.button :submit, class: "mt-3 btn btn-primary w-100" %>
<% end %>

app/views/categories/edit.html.erb
<div class="modal-header">
  <%= turbo_frame_tag 'modal' do %>
    <h2 class="modal-header">Edit category</h2>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    <div class="modal-body">
      <%= render 'form', category: @category %>
    </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="page-header d-print-none">
  <div class="container-xl">
    <div class="row g-2 align-items-center">
      <div class="col">
        <h3 class="page-title">Categories</h3>
      </div>
      <div class="col-auto ms-auto">
        <div class="btn-list">
          <%= link_to new_category_path, data: { turbo_frame: 'modal' }, class: 'btn btn-primary' do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 5l0 14"></path><path d="M5 12l14 0"></path></svg>Add new category
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="page-body">
  <div class="container-xl">
    <div class="col-12">
      <div class="card">
        <div class="table-responsive">
          <table class="table card-table table-vcenter text-nowrap datatable">
            <thead>
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Transactions</th>
                <th scope="col">Created at</th>
                <th scope="col">Updated at</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
              <%= render @categories %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="container-xl my-3">
    <%= paginate @categories, theme: 'bootstrap-5', pagination_class: "pagination-sm flex-wrap justify-content-center" %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="modal-header">
  <%= turbo_frame_tag 'modal' do %>
    <h2 class="modal-header">Add new category</h2>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    <div class="modal-body">
      <%= render 'form', category: @category %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Cash Flow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://rsms.me/">
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-0SPWQM395B"></script>
    <%= javascript_include_tag 'analytics', async: true %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body class="theme-light" data-controller="theme">
    <div class="page">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <div class="page-wrapper">
        <%= yield %>
        <div
          class="modal fade"
          tabindex="-1"
          data-controller="modal"
          data-action="turbo:frame-load->modal#open turbo:submit-end->modal#close"
          >
          <div class="modal-dialog">
            <div class="modal-content">
              <%= turbo_frame_tag "modal" %>
            </div>
          </div>
        </div>
      </div>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<header class="navbar navbar-expand-md navbar-light d-print-none">
  <div class="container-xl">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
      <%= link_to root_path do %>
        My Cash Flow
      <% end %>
    </h1>
    <div class="navbar-nav flex-row order-md-last">
      <div class="nav-item d-none d-md-flex me-3">
      </div>
      <div class="d-none d-md-flex">
        <a href="#" data-action="click->theme#switch" data-theme-value='dark' class="nav-link px-0 hide-theme-dark" data-bs-toggle="tooltip" data-bs-placement="bottom" aria-label="Enable dark mode">
          <!-- Download SVG icon from http://tabler-icons.io/i/moon -->
          <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 3c.132 0 .263 0 .393 0a7.5 7.5 0 0 0 7.92 12.446a9 9 0 1 1 -8.313 -12.454z"></path></svg>
        </a>
        <a href="#" data-action="click->theme#switch" data-theme-value='light' class="nav-link px-0 hide-theme-light" data-bs-toggle="tooltip" data-bs-placement="bottom" aria-label="Enable light mode">
          <!-- Download SVG icon from http://tabler-icons.io/i/sun -->
          <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 12m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"></path><path d="M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7"></path></svg>
        </a>
      </div>
      <% if user_signed_in? %>
        <div class="nav-item dropdown">
          <%= link_to '#', class: "nav-link d-flex lh-1 text-reset p-0", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false do %>
            <%= image_tag "avatar.jpg", class: "avatar" %>
            <div class="d-none d-xl-block ps-2">
              <div>Username</div>
              <div class="mt-1 small text-muted"><%= current_user.email %></div>
            </div>
          <% end %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</header>
<% if user_signed_in? %>
  <header class="navbar-expand-md">
    <div class="collapse navbar-collapse" id="navbar-menu">
      <div class="navbar navbar-light">
        <div class="container-xl">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to user_root_path, class: 'nav-link' do %>
                <span class="nav-link-icon d-md-none d-lg-inline-block">
                  <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-dashboard" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <path d="M12 13m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path>
                    <path d="M13.45 11.55l2.05 -2.05"></path>
                    <path d="M6.4 20a9 9 0 1 1 11.2 0z"></path>
                  </svg>
                </span>
                <span class="nav-link-title">
                  Dashboard
                </span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to categories_path, class: 'nav-link' do %>
                <span class="nav-link-icon d-md-none d-lg-inline-block">
                  <span class="nav-link-icon d-md-none d-lg-inline-block">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-category" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <path d="M4 4h6v6h-6z"></path>
                      <path d="M14 4h6v6h-6z"></path>
                      <path d="M4 14h6v6h-6z"></path>
                      <path d="M17 17m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
                    </svg>
                  </span>
                </span>
                <span class="nav-link-title">
                  Categories
                </span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to accounts_path, class: 'nav-link' do %>
                <span class="nav-link-icon d-md-none d-lg-inline-block">
                  <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-businessplan" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <path d="M16 6m-5 0a5 3 0 1 0 10 0a5 3 0 1 0 -10 0"></path>
                    <path d="M11 6v4c0 1.657 2.239 3 5 3s5 -1.343 5 -3v-4"></path>
                    <path d="M11 10v4c0 1.657 2.239 3 5 3s5 -1.343 5 -3v-4"></path>
                    <path d="M11 14v4c0 1.657 2.239 3 5 3s5 -1.343 5 -3v-4"></path>
                    <path d="M7 9h-2.5a1.5 1.5 0 0 0 0 3h1a1.5 1.5 0 0 1 0 3h-2.5"></path>
                    <path d="M5 15v1m0 -8v1"></path>
                  </svg>
                </span>
                <span class="nav-link-title">
                  Accounts
                </span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to transactions_path, class: 'nav-link' do %>
                <span class="nav-link-icon d-md-none d-lg-inline-block">
                  <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-premium-rights" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
                    <path d="M13.867 9.75c-.246 -.48 -.708 -.769 -1.2 -.75h-1.334c-.736 0 -1.333 .67 -1.333 1.5c0 .827 .597 1.499 1.333 1.499h1.334c.736 0 1.333 .671 1.333 1.5c0 .828 -.597 1.499 -1.333 1.499h-1.334c-.492 .019 -.954 -.27 -1.2 -.75"></path>
                    <path d="M12 7v2"></path>
                    <path d="M12 15v2"></path>
                  </svg>
                </span>
                <span class="nav-link-title">
                  Transactions
                </span>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </header>
<% end %>

app/views/transactions/_import.html.erb
<%= simple_form_for(transaction, method: :post, url: import_transactions_path) do |f| %>
  <%= f.association :account, collection: current_user.accounts, label_method: :name, value_method: :id, prompt: "Choose account"%>
  <%= f.label :file, "Upload CSV File", class: 'form-label' %>
  <%= f.file_field :file, class: 'form-control', accept: '.csv', required: true %>
  <%= f.button :submit, 'Import transactions', class: 'btn btn-primary mt-3 w-100' %>
<% end %>

app/views/transactions/_transaction.html.erb
<tr>
  <th scope="row"><%= transaction_counter + 1 %></th>
  <td><%= transaction.date.to_date %></td>
  <td>
    <div class="cell-collapse" data-cell-expand-target="cell">
      <%= transaction.description %>
    </div>
  </td>
  <td class="text-end"><%= number_to_currency(transaction.amount, precision: 2) %></td>
  <td><%= transaction.transaction_type.capitalize %></td>
  <td><%= transaction.category.name %></td>
  <td><%= transaction.account.name %></td>
  <td>
    <div class="cell-collapse" data-cell-expand-target="cell">
      <%= transaction.notes %>
    </div>
  </td>
  <td>
    <%= link_to edit_transaction_path(transaction), class: 'text-primary', data: { turbo_frame: 'modal' } do %><i class="bi bi-pencil-square"></i><% end %>
    <%= link_to transaction_path(transaction), class: 'text-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %><i class="bi bi-trash"></i><% end %>
  </td>
</tr>

app/views/transactions/index.html.erb
<div class="page-header d-print-none">
  <div class="container-xl">
    <div class="row g-2 align-items-center">
      <div class="col">
        <h3 class="page-title">Transactions</h3>
      </div>
      <div class="col-auto ms-auto">
        <div class="btn-list">
          <%= link_to read_transactions_path, data: { turbo_frame: 'modal' }, class: 'btn btn-secondary' do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-table-import" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
              <path d="M4 13.5v-7.5a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-6m-8 -10h16m-10 -6v11.5m-8 3.5h7m-3 -3l3 3l-3 3"></path>
            </svg>Import transactions
          <% end %>
          <%= link_to new_transaction_path, data: { turbo_frame: 'modal' }, class: 'btn btn-primary' do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 5l0 14"></path><path d="M5 12l14 0"></path></svg>Add new transaction
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="page-body">
  <div class="container-xl">
    <div class="col-12">
      <div class="card">
        <div class="table-responsive" data-controller="cell-expand">
          <button type="button" data-cell-expand-target="button" data-action="click->cell-expand#toggle" class="btn btn-ghost-primary btn-sm m-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-plus" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
              <path d="M12 5l0 14"></path>
              <path d="M5 12l14 0"></path>
            </svg>Expand table
          </button>
          <table class="table card-table table-vcenter table-nowrap datatable table-collapse">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Date</th>
                <th scope="col">
                  Description
                </th>
                <th scope="col" class="text-end">Amount</th>
                <th scope="col">Type</th>
                <th scope="col">Category</th>
                <th scope="col">Account</th>
                <th scope="col">Notes</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
              <%= render @transactions %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="container-xl my-3">
    <%= paginate @transactions, theme: 'bootstrap-5', pagination_class: "pagination-sm flex-wrap justify-content-center" %>
  </div>
</div>